"""init

Revision ID: 693f0c6730ab
Revises: 
Create Date: 2025-05-21 12:11:29.765374

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '693f0c6730ab'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('departements',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nom', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('nom')
    )
    op.create_index(op.f('ix_departements_id'), 'departements', ['id'], unique=False)
    op.create_table('formations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('titre', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('theme', sa.String(), nullable=True),
    sa.Column('duree', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_formations_id'), 'formations', ['id'], unique=False)
    op.create_table('etudiants',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nom', sa.String(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('mot_de_passe', sa.String(), nullable=False),
    sa.Column('departement_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['departement_id'], ['departements.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_etudiants_email'), 'etudiants', ['email'], unique=True)
    op.create_index(op.f('ix_etudiants_id'), 'etudiants', ['id'], unique=False)
    op.create_table('etudiant_formation',
    sa.Column('etudiant_id', sa.Integer(), nullable=False),
    sa.Column('formation_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['etudiant_id'], ['etudiants.id'], ),
    sa.ForeignKeyConstraint(['formation_id'], ['formations.id'], ),
    sa.PrimaryKeyConstraint('etudiant_id', 'formation_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('etudiant_formation')
    op.drop_index(op.f('ix_etudiants_id'), table_name='etudiants')
    op.drop_index(op.f('ix_etudiants_email'), table_name='etudiants')
    op.drop_table('etudiants')
    op.drop_index(op.f('ix_formations_id'), table_name='formations')
    op.drop_table('formations')
    op.drop_index(op.f('ix_departements_id'), table_name='departements')
    op.drop_table('departements')
    # ### end Alembic commands ###
